#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2026 FreZeeN
# Part of crt-dual — https://github.com/frezeen
# display-lib.sh — CRT-DUAL dual-output: detection + shared layout
#
# Centralizes video output classification (by CONNECTOR TYPE, never by port
# name) and the runtime dual-output layout. Single source shared by:
# - crt-x11-generator.sh  (per-output mapping in the X config, 99-crt.conf)
# - zz_crt_dual       (runtime layout at boot, layout_apply_if_changed)
#
# Exported variables (after detect_outputs):
# CRT_OUTS            — confirmed analog CRT outputs (connected, no EDID)
# CRT_PRESUMED_OUTS   — disconnected analog outputs (last resort; verified
# by crt_probe after X is up)
# LCD_OUTS            — digital outputs (native LCD), space-separated
# CRT_OUT             — first confirmed analog output (runtime layout)
# CRT_PRESUMED_OUT    — first presumed analog output
# LCD_OUT             — first digital output (runtime layout)
#
# Classification cascade (reliable signal -> presumption as LAST resort):
# digital connected -> LCD | analog + EDID -> LCD | analog connected
# without EDID -> CRT | analog disconnected -> CRT_PRESUMED (test = crt_probe).
#
# Prerequisite: detect_gpu (gpu-lib.sh) must have run before layout_apply_if_changed.
#
# Shell contract: this library is written to be safe under `set -u` and
# `set -o pipefail` (every possibly-unset variable has an explicit default,
# pipelines are failure-tolerant). The caller enables those options — a
# sourced library must NOT set shell options itself (they would mutate the
# caller's shell state; the generator does `set -uo pipefail` before sourcing).
#
# TUBE-SAFETY CONTRACT (why some things are deliberately non-obvious):
# - NEVER `--auto` on the CRT. The DP->VGA converter's fake EDID advertises
# VESA 31kHz modes (640x480@59.94 preferred); --auto would pick it and
# put the tube out of lock (risk of damage). 15kHz modes are set by name
# only (src/owner/sr-owner.sh _crt_set_15khz_direct).
# - 60.00 vs 59.94 matters: the refresh field distinguishes OUR 480i
# (60.00) from the VESA EDID 640x480@59.94 (31kHz). layout-watch uses it
# to detect a gameStop collision and restore the desktop mode.
# - `DefaultModes False` in the CRT Monitor section: suppress the builtin
# VESA modes (31kHz+) on EDID-less ports, so nothing can land 31kHz on
# the tube by accident.
# - 240p fallback on digital ports (converter): when 480i interlace is
# rejected (DP -> ENOENT), fall back to 320x240 + --scale 2x2 so the
# FULL 640x480 desktop stays visible at 240p.
# - gameStop guard: restore_after_game() re-applies the desktop layout
# after a CRT game; MODE_FILE marks an active game so the hotplug
# watcher skips mid-game layout changes.

# The 15kHz CRT mode is "640x480i" (480i), generated by SwitchRes from the
# system ini (/etc/switchres.ini) and written into 99-crt.conf by
# crt-x11-generator.sh. ONE 480i modeline, ONE unique name: the official
# Batocera interlace name "640x480i" (never the bare "640x480" — the kernel
# re-synthesizes its own "640x480" 54MHz DoubleScan / 25.175MHz @59.94 on
# the analog re-probe; a shared name made --mode nondeterministic and the
# tube went black at boot, verified 2026-08-12 AMD R9 270X).
# Scope: this name is the CONF/BOOT contract only (X attaches it itself at
# startup). Mode names are owned by their generator: at runtime the desktop
# is the engine-issued SR-* handle — no path requests "640x480i" by name
# (NVIDIA renames WxH-like conf names to the bare form and BadMatches their
# runtime re-add, verified 2026-08-28 GTX 970; the same literal that reads
# correctly on AMD aborts a whole batch client-side on NVIDIA).

# Classification by CONNECTOR TYPE (no hardcoded port names).
# Analog  -> 15kHz CRT:  DVI-I, VGA, CRT
# Digital -> native LCD: HDMI, DVI-D, DisplayPort, eDP
# NOTE: on NVIDIA sysfs exposes no EDID (0 bytes), but xrandr --prop does
# (verified live: HDMI-0 LCD exposes the EDID block, DVI-I-0 CRT does not).
# The base classification is by connector type; EDID (post-X) and the
# crt-dual.analog_lcd=1 override refine the LCD-on-analog-port case.
# A CRT on a pure digital port (DVI-D/HDMI/DP) cannot be auto-detected:
# it must be wired to the analog port (DVI-I/VGA).
# TEST SEAM: dry-run tests read the DRM connector tree from fixtures, never
# from the live box (tests/run.sh sets CRT_DUAL_SYSFS to a fixture tree;
# default = the kernel interface, so stock behavior is unchanged).
# Used by _detect_outputs_sysfs and _sysfs_status below.
CRT_DUAL_SYSFS="${CRT_DUAL_SYSFS:-/sys/class/drm}"

# ── GPU ADAPTER CONTRACT (2026-08-23) ─────────────────────────────
# Shared code NEVER branches on the GPU family for truth questions; it
# asks the ADAPTER (src/lib/gpu/<vendor>.sh, lazy-sourced once). Each
# adapter declares its ONE oracle per question in its header — NVIDIA is
# pure-X, AMD/Intel are sysfs-truth families with their documented
# quirks; generic.sh = conservative fallback (pre-detection calls).
LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# detection pure helpers live in display-detect.sh
[ -r "$LIB_DIR/display-detect.sh" ] && source "$LIB_DIR/display-detect.sh" 2>/dev/null || true
GPU_ADAPTER_FILE=""
_gpu_adapter() { # source the family adapter exactly once per process
	[ -n "${GPU_VENDOR:-}" ] || GPU_VENDOR="$(lspci 2>/dev/null | grep -qi nvidia && echo nvidia || echo generic)"
	local _f="$GPU_VENDOR"
	case "$_f" in amd | intel | nvidia) ;; *) _f=generic ;; esac
	_f="$LIB_DIR/gpu/$_f.sh"
	[ "$GPU_ADAPTER_FILE" = "$_f" ] && return 0
	if [ -f "$_f" ]; then
		# shellcheck disable=SC1090
		source "$_f" && GPU_ADAPTER_FILE="$_f"
	else
		source "$LIB_DIR/gpu/generic.sh" && GPU_ADAPTER_FILE="$LIB_DIR/gpu/generic.sh"
	fi
}
_EDID_PROPS_CACHE="" # adapter-owned --prop snapshot (refreshed per detect)

# Trampolines — stable shared API; the family adapter owns each answer.
_edid_present() { # <xout> -> 0|1 : EDID evidence per the family oracle
	_gpu_adapter || return 1
	_impl_edid "$1"
}
_mode_inject_default() { # index-form API create + RandR attach, with read-back verify
	# Source-confirmed (upstream master, custom_video_xrandr.cpp:470-536):
	# the xrandr backend selects a display ONLY if connected AND holding a
	# CRTC; a connected-but-modeless output is skipped -> "no screen
	# detected". Index-form binding passes "0" as the positional screen_pos
	# clause, so it binds the FIRST valid output (the LCD) instead - and X
	# user modes are SCREEN-GLOBAL, so the fresh SR-* mode lands in the
	# global mode space reachable by any output. The API stays the single
	# source of timing+name; one RandR --addmode attaches it to the TARGET
	# output - plumbing the library cannot cover for an output it did not
	# bind, never a second generator. Select-first still owns the mode:
	# next cycle re-certifies instead of re-injecting.
	local target="${1:-}" api out
	[ -z "$target" ] && return 1
	[ -n "${DISPLAY:-}" ] || export DISPLAY=:0
	api=$(_switchres_api_path)
	[ -r "$api" ] || return 1
	out=$(python3 "$api" create 640 480 "${CRT_DUAL_REFRESH:-60}" 0 --ini /etc/switchres.ini 2>/dev/null) || return 1
	case "$out" in SR-*) ;; *) return 1 ;; esac
	xrandr --addmode "$target" "$out" 2>/dev/null || return 1
	# read-back verify (no silent best-effort on a step the contract
	# depends on)
	xrandr --current 2>/dev/null | sed -n "/^$target connected/,/^[^ ]/p" | grep -q "$out" || return 1
	echo "$out"
}
_desktop_mode_name() {
	# Runtime NAME of the 15kHz desktop mode (the persistent conf
	# Modeline "640x480i") — a FAMILY fact, owned by the adapter:
	# modesetting keeps conf names verbatim ("640x480i"); NVIDIA presents
	# the same interlaced mode under the bare "640x480" alias and rejects
	# resolution-shaped suffixed re-adds (RRAddOutputMode BadMatch,
	# measured 2026-08-28 GTX 970). Shared code never hardcodes either.
	_gpu_adapter && _impl_desktop_mode_name
}
_crt_desktop_ensure() { # <out> -> echo the ATTACHABLE 480i desktop name for <out>
	# One resolution rule, all families (converges every boot topology to
	# the certified dual-boot flow): (1) the conf-family name when the
	# driver actually pooled it — every certified boot-time-connected flow
	# keeps its exact stream; (2) else the SR session mode the injector
	# created at bind — a late-plugged analog NEVER gets the conf mode
	# pooled (NVIDIA publishes conf modelines only for outputs connected
	# at X start; Xorg.0.log 12:33 boot 2026-08-30: MetaModes applied at
	# start on the disconnected port, mode absent from the pool after the
	# plug — dual restore/gameStart then died on "cannot find mode
	# 640x480"); (3) else ensure-inject (create+attach+read-back verify).
	# rc=1 loud when nothing is attachable — never a name fallback, never
	# a name literal in shared code (the conf name comes from the adapter
	# trampoline, the SR name from the shared injector).
	local target="$1" _pool _dn _sr
	[ -n "$target" ] || return 1
	[ -n "${DISPLAY:-}" ] || export DISPLAY=:0
	_pool=$(xrandr --current 2>/dev/null | sed -n "/^$target connected/,/^[^ ]/p")
	_dn=$(_desktop_mode_name 2>/dev/null)
	if [ -n "$_dn" ] && printf '%s\n' "$_pool" | grep -qE "(^|[[:space:]])${_dn}([[:space:]]|$)"; then
		echo "$_dn"
		return 0
	fi
	_sr=$(printf '%s\n' "$_pool" | grep -oE 'SR-[0-9]+_640x480@[0-9.]+i' | head -1)
	[ -n "$_sr" ] && { echo "$_sr"; return 0; }
	_mode_inject_default "$target"
}
_desktop_mode_spec() {
	# Echoes "NAME RATE" for the 15kHz desktop: NAME from the family
	# adapter (_desktop_mode_name), RATE from the DYNAMIC tube flag
	# crt-dual.refresh (60 NTSC / 50 PAL) — never hardcoded, read at call
	# time (universal-cross-gpu §3). One spec source for every apply path.
	local _dn _r
	_dn=$(_desktop_mode_name) || return 1
	_r=$(grep -E '^crt-dual\.refresh[[:space:]]*=' "$CRT_DUAL_BATOCERA_CONF" 2>/dev/null | tail -1 | sed 's/.*=//' | tr -d '[:space:]')
	[ -z "$_r" ] && _r=60
	echo "$_dn $_r"
}

# Runtime state directory: /tmp/crt-dual by default (live box). The test
# harness overrides it (CRT_DUAL_STATE_DIR) so dry-run cases never write
# the live /tmp/crt-dual-* state (observed 2026-08-12: the harness's
# detect_outputs with NVIDIA fixtures overwrote the live detect-state ->
# the running watcher light-retried on a phantom port name).
: "${CRT_DUAL_STATE_DIR:=/tmp/crt-dual}"
# The runtime state lives in /tmp and the OS wipes it at every boot — the
# lib's lock/fingerprint/detect-state writers must NOT silently fail when
# the dir is gone (verified 2026-08-12: after a reboot the apply's
# layout.lock open failed -> the dual was never applied -> the stock
# side-by-side layout stayed, the LCD showed the desktop's empty right
# half). Creating it here covers every consumer that sources the lib
# (watcher, service, selector, diag).
mkdir -p "${CRT_DUAL_STATE_DIR}" 2>/dev/null || true # best-effort; /tmp may be read-only in exotic setups

# batocera.conf path (test seam: point it at a fixture; live default).
# NOTE: CRT_DUAL_CONF is the X11 generator's OUTPUT path — never reuse it.
: "${CRT_DUAL_BATOCERA_CONF:=/userdata/system/batocera.conf}"

# ── Timing constant (named — the number measures LATENCY/DEBOUNCE on
# dce_v6's broken analog path, not performance: the board has no analog
# HPD (shared pin), a driver poll ~10 min late, a load-sense that can
# flake, and a latch that accepts modesets into an empty port. The
# defensive value is WHY the code can read as "over-fitted to AMD" —
# it IS: dce_v6 is the only GPU whose analog path needs this; the
# mechanism it protects (kernel-truth + live-evidence) is universal.
# Re-verify on the real hardware before changing it. ──
DEMOTE_DEBOUNCE_SEC=1        # demote debounce: two disconnected reads apart (probe-race)

# Explicit override: crt-dual.analog_lcd=1 in batocera.conf -> analog ports
# (VGA/DVI-I) are treated as LCD. Escape hatch for an LCD on VGA at pre-X
# boot, where EDID is unreadable (NVIDIA sysfs = 0 bytes) and 99-crt.conf
# (HorizSync 15-17) would reject the LCD's EDID modes.
_crt_dual_analog_lcd() {
	local _v
	[ -f "$CRT_DUAL_BATOCERA_CONF" ] || return 1
	# The LAST occurrence is the effective value (batocera-settings APPENDS).
	_v=$(grep -E "^crt-dual\.analog_lcd[[:space:]]*=" "$CRT_DUAL_BATOCERA_CONF" 2>/dev/null | tail -1 | cut -d= -f2- | tr -d ' "[:space:]')
	[ "$_v" = "1" ]
}

# Explicit override: crt-dual.crt_output=<port> in batocera.conf -> that
# port is a CONFIRMED CRT (user declaration). For CRTs on pure digital
# ports behind a converter (e.g. physical VGA driven by a DP on
# Intel/HP 800 G5): auto-detection cannot see them (disconnected, no EDID),
# but the user KNOWS where the CRT is. Highest precedence over the cascade.
# CRT_DUAL_CRT_OUTPUT = port (or empty). Not in CRT_KEYS -> persists.
_crt_dual_crt_output() {
	CRT_DUAL_CRT_OUTPUT=""
	[ -f "$CRT_DUAL_BATOCERA_CONF" ] || return 1
	local v
	# The LAST occurrence is the effective value (batocera-settings APPENDS).
	v=$(grep -E "^crt-dual\.crt_output[[:space:]]*=" "$CRT_DUAL_BATOCERA_CONF" 2>/dev/null | tail -1 | cut -d= -f2- | tr -d ' "')
	[ -n "$v" ] || return 1
	CRT_DUAL_CRT_OUTPUT="$v"
	return 0
}

# Analog port with a valid EDID block in xrandr --prop -> it is an LCD
# (CRTs rarely expose EDID over DDC; verified: DVI-I-0 CRT has no EDID).
# Post-X only (needs xrandr --prop). Returns 0 if the output has a valid
# EDID (magic 00ffffffffffff00 on the first line of the block).
_output_has_edid() {
	local props="$1" out="$2" hex
	hex=$(printf '%s\n' "$props" | awk -v o="$out" '
		$0 ~ "^" o " connected" { hit=1; next }
		hit && /^[^ \t]/ { exit }
		hit && /EDID:/ { edid=1; next }
		hit && edid && /^[ \t]+[0-9a-fA-F]+/ { print $1; exit }
	')
	[ -n "$hex" ] && echo "$hex" | grep -q "^00ffffffffffff00"
}

# EDID of an X output: sysfs edid file (kernel) first — the AMD/Intel
# truth. NVIDIA sysfs keeps 0 bytes even for LCDs (verified GTX 970:
# xrandr --prop carries the block) -> the caller falls back to a LAZY
# xrandr --prop, fetched ONCE per detect (not a full scan per output like
# _edid_reclassify used to do — removed 2026-08-12).
_sysfs_edid_present() {
	local f sz
	for f in "$CRT_DUAL_SYSFS"/card*-"$(_drm_connector "$1")"/edid; do
		[ -f "$f" ] || continue
		# sysfs st_size LIES (reports 0 for a 256-byte edid) and the EDID
		# block starts with 0x00 (nulls are stripped by $()) — count the
		# bytes actually READ with wc -c (verified 2026-08-12 AMD).
		sz=$(wc -c <"$f" 2>/dev/null)
		[ -n "$sz" ] && [ "$sz" -gt 0 ] 2>/dev/null && return 0
	done
	return 1
}

# ANY readable sysfs edid in the system = sysfs DDC is trustworthy
# (amd/intel) -> skip the xrandr --prop lazy fallback (GLITCH-class,
# measured 2026-08-12). Only when ALL edid files are empty on read
# (NVIDIA: sysfs edid 0 bytes even for LCDs, verified 2026-08-11) does
# --prop carry the only block. Vendor-independent — works even when
# detect_gpu never ran (selector/apply/remove source display-lib alone).
_sysfs_has_any_edid() {
	local f sz
	for f in "$CRT_DUAL_SYSFS"/card*/edid; do
		[ -f "$f" ] || continue
		sz=$(wc -c <"$f" 2>/dev/null)
		[ -n "$sz" ] && [ "$sz" -gt 0 ] 2>/dev/null && return 0
	done
	return 1
}

# Shared DRM->X mapping for the X name -> sysfs connector lookup (one
# function, both _sysfs_status and the EDID lookup use it — never re-create
# the mapping). NVIDIA: X index = DRM index-1 (X DVI-I-0 =
# DRM DVI-I-1, X DP-0 = DRM DP-1); AMD/Intel: identity (Intel X "HDMI-1" =
# DRM "HDMI-A-1"). The NVIDIA offset is a measured driver fact (GTX 970,
# verified) — the universal rename (type-order pairing, no vendor branch)
# is a separate, test-guarded step.
_drm_connector() {
	local out="$1" type idx drm
	type="${1%-*}" # shortest suffix: "DVI-I-0" -> "DVI-I" (NOT ${1%%-*} — that longest-suffix cut produced "DVI" and the DVI-I) case never matched; masked pre-2026-08-12 while analog classification came from the xrandr listing, exposed by the sysfs-truth rewrite + caught by the harness)
	idx="${1##*-}"
	case "$type" in
	HDMI) drm="HDMI-A-${idx}" ;;
	DVI-I) drm="DVI-I-${idx}" ;;
	*) drm="${type}-${idx}" ;;
	esac
	# FAMILY MAPPING FACT: DRM connector index vs X index (+1 on NVIDIA,
	# measured GTX 970; identity elsewhere). The universal rename is a
	# separate, test-guarded step.
	idx=$((idx + $(_gpu_adapter && _impl_drm_offset)))
	case "$type" in
	HDMI) drm="HDMI-A-${idx}" ;;
	DVI-I) drm="DVI-I-${idx}" ;;
	*) drm="${type}-${idx}" ;;
	esac
	echo "$drm"
}

# Reverse mapping: DRM (sysfs connector) name -> X output name. The inverse
# of _drm_connector() — same single-source rule, kept adjacent: "HDMI-A-1"
# -> "HDMI-1" (kernel "-A-" quirk), NVIDIA DRM DVI-I-1 -> X DVI-I-0
# (index-1). Used by crt-x11-generator.sh for the Disabled-output list:
# the sysfs enumerates EVERY connector (kernel truth — xrandr cannot: the
# current X already hides the Disabled outputs, so a regen from xrandr
# would drop the very options that kill the phantoms, verified 2026-08-12).
_drm_to_x() {
	local drm="$1" type idx
	case "$drm" in
	HDMI-A-*)
		type="HDMI"
		idx="${drm#HDMI-A-}"
		;;
	*)
		type="${drm%-*}"
		idx="${drm##*-}"
		;;
	esac
	# FAMILY MAPPING FACT (mirror of _drm_connector): DRM index vs X index.
	idx=$((idx - $(_gpu_adapter && _impl_drm_offset || echo 0)))
	echo "${type}-${idx}"
}
# ──────────────────────────────────────────────────
# OUTPUT DETECTION — cascade (reliable signal -> presumption as LAST resort)
#
# For every present output, by reliability order:
# 1. Digital (HDMI/DP/DVI-D/eDP) connected + EDID  -> LCD confirmed
# 2. Analog (VGA/DVI-I/CRT) connected + EDID      -> LCD on analog (dynamic)
# 3. Analog connected WITHOUT EDID                -> CRT confirmed (driver senses the cable)
# 4. Analog DISCONNECTED (LAST resort)            -> CRT_PRESUMED: no reliable
# signal; assume CRT (analog port exists) and the TEST (crt_probe,
# post-X) confirms port liveness or rolls back to stock.
#
# 5. Digital connected WITHOUT EDID (only when no analog port) -> CRT_PRESUMED:
# suspected CRT behind a converter (e.g. physical VGA driven by a DP on
# Intel/HP 800 G5). The probe (connected -> hotplug) confirms it.
# 6. Digital DISCONNECTED (only when no analog port) -> CRT_PRESUMED:
# the port is a DP->VGA converter (no EDID -> "disconnected"); the
# probe (640x480 modeset) verifies whether it is drivable.
#
# Gate 5/6: if an analog port (VGA/DVI-I) EXISTS, digitals cannot be CRTs —
# a CRT on digital requires a converter and auto-detect cannot distinguish
# it from an empty port (only the crt-dual.crt_output override applies there).
#
# Variables: CRT_OUTS (confirmed), CRT_PRESUMED_OUTS (presumed), LCD_OUTS.
# The probe (crt_probe) promotes drivable PRESUMED ports to CONFIRMED
# (/tmp/crt-dual-probe-ok -> re-read by detect_outputs): without promotion, a
# presumed port + LCD stays LCD-only (a detached port with
# LCD = empty, not CRT).
# ──────────────────────────────────────────────────
# 15kHz-class ACTIVE modeline on an output = the kernel is outputting a
# CRT timing RIGHT NOW — the one analog signal that cannot go stale.
# NAME classes that count: 640x480i (desktop), 320x240 (240p fallback),
# SR-* (game native). NOT a CRT: the VESA no-sink 640x480@59.94, the
# 54MHz DoubleScan "640x480", the NVIDIA replug @75. On NVIDIA the bare
# shadowed name needs the ACTIVE Interlace flag instead — family fact,
# canonical story lives in src/lib/gpu/nvidia.sh (ModePool shadowing).
_crt_active_15khz() {
	local out="$1" name
	[ -n "$out" ] || return 1
	name=$(_xrandr_active_mode "$out" name) || return 1
	case "$name" in
	640x480i | 320x240 | SR-*) return 0 ;;
	esac
	# NAME match failed -> ask the FAMILY ORACLE for active-mode truth.
	# On NVIDIA the driver exposes the analog CRT interlace under the bare
	# name "640x480" and refuses aliased modelines on the analog port
	# (ModePool shadowing, BadMatch), so the name match above can never
	# fire there: nvidia.sh reads the ACTIVE mode's Interlace flag via
	# --verbose (glitch-FREE on this stack — dce_v6 blips are AMD-only).
	# amd/intel/generic return 1: their desktop modes carry 15kHz names,
	# --verbose stays unreached (keeps the dce_v6 tube glitch-free).
	_gpu_adapter && _impl_crt_active_truth "$out"
}

# Single source of "is this output analog?" — the ONE predicate the
# detection cascade, the mode setters and the watcher guard MUST agree
# on. 2026-08-19: the bug was exactly two re-derivations disagreeing —
# the EDID-garbage->converter gate in _crt_set_15khz_direct treated a
# bare analog CRT (no EDID -> full VESA mode list) as a digital converter
# and refused 480i, while the analog/digital discrimination lower in the
# same function would have called it analog. One helper everywhere
# removes the disagreement class by construction. Accepts an X output
# name ("DVI-I-0") or a DRM connector name ("DVI-I-1") — shortest-
# suffix type cut (${var%-*}).
_output_is_analog() {
	local out="${1:-}"
	[ -n "$out" ] || return 1
	case "${out%-*}" in # shortest suffix: "DVI-I-0" -> "DVI-I"
	DVI-I | VGA | CRT) return 0 ;;
	*) return 1 ;;
	esac
}

detect_outputs() {
	CRT_OUTS=""
	CRT_PRESUMED_OUTS=""
	LCD_OUTS=""
	CRT_OUT=""
	CRT_PRESUMED_OUT=""
	LCD_OUT=""
	_EDID_PROPS_CACHE="" # fresh oracle snapshot per detection cycle

	if [ -n "${DISPLAY:-}" ] && command -v xrandr >/dev/null 2>&1; then
		_detect_outputs_xrandr
		# X is up but xrandr produces no outputs (X down / wrong DISPLAY) ->
		# sysfs fallback: classification must not stay empty
		# (verified live: X dead at boot -> empty PASSO 7 dump).
		if [ -z "$CRT_OUTS$CRT_PRESUMED_OUTS$LCD_OUTS" ]; then
			_detect_outputs_sysfs
		fi
		# KERNEL TRUTH for LCD removal: xrandr's "connected" can be a
		# PHANTOM right after a physical unplug (X lags sysfs by seconds —
		# verified 2026-08-11 friend's Intel UHD 630: LCD detached, sysfs
		# said disconnected, xrandr still listed DP-1 connected -> the
		# watcher applied the DUAL layout with the CRT at +2560 (right of
		# the gone LCD) -> CRT black on screen. The sysfs status is the
		# kernel truth: an LCD output that sysfs reports disconnected is
		# GONE — drop it from LCD_OUTS so the layout goes CRT-only.
		# (CRTs stay: a CRT behind a converter legitimately reports
		# disconnected with no EDID — that is exactly the presumed/probe
		# path. LCDs always have EDID and a real hotplug signal.)
		_detect_filter_lcd_phantom
	else
		# sysfs fallback (pre-X boot, DISPLAY not exported)
		_detect_outputs_sysfs
	fi

	# Post-classify: 7 helpers pure in display-detect.sh (T15.1 slim)
	_detect_apply_override
	_detect_promote_live
	_detect_promote_probe
	_detect_promote_replug
	_detect_demote
	_detect_escape_analog_lcd
	# Recompute the singles (override/promotion/escape may have
	# invalidated them — without this the layout would use the first
	# PRESUMED port).
	CRT_OUT=$(echo "$CRT_OUTS" | awk '{print $1}')
	CRT_PRESUMED_OUT=$(echo "$CRT_PRESUMED_OUTS" | awk '{print $1}')
	LCD_OUT=$(echo "$LCD_OUTS" | awk '{print $1}')

	# State file for non-bash consumers — the SINGLE authoritative
	# role->port mapping (lists AND the resolved singles). Every consumer
	# (watcher _crt_port/_lcd_port, Python selector, diag) reads this one
	# handoff; nobody re-derives "which output is the CRT/LCD" from raw
	# xrandr or re-splits the lists (2026-08-19 #2 consolidation: stale or
	# missing file degrades to env/empty, never to a wrong port). Additive
	# lines — older readers ignoring the singles are unaffected.
	{
		echo "CRT_OUTS=${CRT_OUTS:-}"
		echo "CRT_PRESUMED_OUTS=${CRT_PRESUMED_OUTS:-}"
		echo "LCD_OUTS=${LCD_OUTS:-}"
		echo "CRT_OUT=${CRT_OUT:-}"
		echo "CRT_PRESUMED_OUT=${CRT_PRESUMED_OUT:-}"
		echo "LCD_OUT=${LCD_OUT:-}"
	} >"$CRT_DUAL_STATE_DIR/detect-state" 2>/dev/null || true # state file is advisory; consumers handle absence

	# Classification log (self-sufficient logs)
	echo "CRT-DUAL-DETECT: confirmed=[${CRT_OUTS:-}] presumed=[${CRT_PRESUMED_OUTS:-}] LCD=[${LCD_OUTS:-}]" >&2
}

# xrandr path: now a thin wrapper over pure helper (T15.1 slim)
_detect_outputs_xrandr() {
	_detect_xrandr_pure "${1:-}" "$CRT_DUAL_SYSFS"
}

# All effective CRT outputs (confirmed + presumed) — used by the
# X11 generator and the layout.
crt_all() {
	echo "$CRT_OUTS $CRT_PRESUMED_OUTS"
}

# Fallback without DISPLAY: reads /sys/class/drm. Same cascade as the
# xrandr path: digital connected -> LCD; analog connected -> CRT confirmed;
# analog PRESENT but not connected -> CRT_PRESUMED (last resort);
# digital disconnected (only without analog ports) -> CRT_PRESUMED
# (CRT candidate behind a converter, post-X probe).
# X name: NVIDIA shifts indices by -1 (DRM card0-DVI-I-1 -> X DVI-I-0,
# verified); AMD/Intel keep the DRM index (Intel verified: DRM
# DP-1/HDMI-A-1 -> X DP-1/HDMI-1 on HP 800 G5, diag 2026-08-09).
# sysfs path now thin wrapper over pure helper (T15.1 slim)
_detect_outputs_sysfs() {
	_detect_sysfs_pure "${1:-$CRT_DUAL_SYSFS}"
}

# ──────────────────────────────────────────────────
# PROBE — the TEST of presumption (last resort)
# Post-X (X active). For every PRESUMED output (detached analog, or
# digital without analog ports — CRT candidate behind a converter):
#
# SYSFS connector state (kernel truth): connected = real hotplug
# -> CRT confirmed. A sysfs-DISCONNECTED port is NEVER promoted.
#
# The old 640x480 modeset test is GONE as evidence — it was wrong on
# dce_v6 (AMD R9 270X, fire-tested 2026-08-12): the driver ACCEPTS any
# modeset into the EMPTY port (the latch — 320x240 accepted with the
# VGA cable out), so "modeset OK" proves nothing about a sink being
# there. Worse, the probe's own modeset leaves the CRTC emitting 480i
# into the empty port, CREATING the live-timing evidence the next
# detect_outputs reads to self-promote the phantom (observed
# 2026-08-13: the stale X config drove 640x480i on the empty DVI-I ->
# "active timing 15kHz-class -> CRT confirmed" -> CRT-only layout ->
# LCD disabled). The modeset discriminates ONLY on drivers that reject
# empty-port modesets (NVIDIA GTX 970) — not universal, so it confirms
# nothing anywhere.
#
# A converter CRT the kernel does not see (DP->VGA active adapter:
# sysfs disconnected, no EDID — the AUX link never trains on dce_v6,
# verified 2026-08-13) is covered by crt-dual.crt_output=<port>: auto-
# detect cannot distinguish a converter from an empty port.
#
# EVIDENCE: ports that PASS are written to /tmp/crt-dual-probe-ok;
# detect_outputs() promotes them to CONFIRMED CRTs (the layout and the
# selector gate must see them — without promotion, presumed+LCD = LCD-only).
# Called by the boot service (PASSO 7) and by diag-dump.sh.
# ──────────────────────────────────────────────────

# FAMILY STATUS ORACLE (adapter contract): presence of an X output as
# the ACTIVE family sees it — sysfs raw on AMD/Intel, X token on NVIDIA
# (see src/lib/gpu/*.sh headers for each family's evidence). Callers:
# promote/demote debounce, digital classification, LCD post-filter.
_sysfs_status() {
	_gpu_adapter || return 1
	_impl_status "$1"
}

# RAW sysfs connector fingerprint ("DVI-I-0:connected HDMI-0:connected ...")
# — the channel AMD/Intel adapters fingerprint; NOT the family oracle
# itself (that is _layout_fingerprint -> _impl_fingerprint).
_sysfp_raw() {
	local _f _drm _x _s _out=""
	for _f in "$CRT_DUAL_SYSFS"/card*-*/status; do
		[ -f "$_f" ] || continue
		_drm=$(basename "$(dirname "$_f")")
		_drm=${_drm#card*-}
		_x=$(_drm_to_x "$_drm" 2>/dev/null) || continue
		[ -n "$_x" ] || continue
		_s=$(cat "$_f" 2>/dev/null | tr -d '[:space:]')
		[ -n "$_s" ] || continue
		_out="$_out $_x:$_s"
	done
	echo "$_out" | tr ' ' '\n' | sort | tr '\n' ' ' | sed 's/^ //'
}

# (moved to the family adapters: src/lib/gpu/*.sh — _impl_fingerprint)

# Active mode of an X output from xrandr --current (glitch-free: the
# old --query forced a connector re-probe and blipped the dce_v6 tube,
# glitch test 2026-08-12: --query=YES, --current=no). Prints
# "<name> <refresh>" (e.g. "640x480 60.00", current/preferred markers
# stripped). Optional $2="name" prints only the mode name. The xrandr
# exit code lies — the effective mode is truth.
# The compact listing shows a mode's refresh rates on ONE line
# ("640x480  75.00  60.00*") — the active rate is the field carrying the
# '*', which is NOT always field 2 (misread as 75.00 while 480i 60.00 was
# active, 2026-08-10, GTX 970 -> false 240p fallbacks). Scan the fields.
# X connector state from xrandr --current (glitch-free cached path):
# 1 = connected, 0 = disconnected, empty = output not listed. On NVIDIA the
# watcher's --query loop keeps this compiler-fresh for the analog ports (the
# only channel that reflects an NVIDIA replug).
_xrandr_connected() {
	xrandr --display "${DISPLAY:-:0}" --current 2>/dev/null | awk -v o="$1" '$1==o {print ($2=="connected" ? 1 : 0); exit}'
}

_xrandr_active_mode() {
	local out="$1" want="${2:-full}" mode
	mode=$(xrandr --display "${DISPLAY:-:0}" --current 2>/dev/null |
		sed -n "/^$out connected/,/^[^ ]/p" | grep '\*' | head -1 |
		awk '{ for (i = 2; i <= NF; i++) if ($i ~ /\*/) { gsub(/[*+]/, "", $i); print $1, $i; exit } }')
	[ -n "$mode" ] || return 1
	if [ "$want" = "name" ]; then
		echo "${mode%% *}"
	else
		echo "$mode"
	fi
}

# Primary output of the X screen (the batocera-resolution anchor,
# PSCREEN=$(xrandr --listPrimary), batocera-resolution:18). Parsed from
# xrandr --current ("DVI-I-1 connected primary ...") — glitch-free: the
# stock --listPrimary forces a connector re-probe that blips the dce_v6
# tube (glitch test 2026-08-12). Prints the output name or nothing.
_xrandr_primary() {
	xrandr --display "${DISPLAY:-:0}" --current 2>/dev/null |
		sed -n '/ connected primary /p' | head -1 | awk '{print $1}'
}

# Single helper for the universal --noprimary-first lesson (verified 2026-08-11
# Intel UHD 630 BadMatch when LCD held large mode): clears the current primary
# before a new --primary, no per-GPU branch, no framebuffer touch.
_primary_clear_for() {
	local want="$1" cur
	cur=$(_xrandr_primary 2>/dev/null)
	if [ -n "$cur" ] && [ "$cur" != "$want" ]; then
		xrandr --display "${DISPLAY:-:0}" --output "$cur" --noprimary 2>/dev/null || true
	fi
}

crt_probe() {
	export DISPLAY="${DISPLAY:-:0}"
	[ -n "$CRT_PRESUMED_OUTS" ] || return 0
	local out ok="" st
	for out in $CRT_PRESUMED_OUTS; do
		# Kernel truth only: a presumed port is a CRT when the kernel
		# reports it CONNECTED (real hotplug). A sysfs-disconnected port
		# stays PRESUMED — no modeset test (dce_v6 latch: empty-port
		# modesets succeed, and the probe's own modeset would create the
		# live-timing evidence the next detect reads to self-promote the
		# phantom, 2026-08-13). With an LCD, presumed+LCD = LCD-only
		# (this invariant is guard-tested).
		st="$(_sysfs_status "$out")"
		if [ "$st" = "connected" ]; then
			echo "CRT-DUAL-PROBE: $out — sysfs connected (REAL hotplug) -> CRT confirmed"
			ok="$ok $out"
		else
			echo "CRT-DUAL-PROBE: $out — sysfs ${st:-absent} (no real hotplug) -> NOT promoted, stays presumed; if the CRT is here: crt-dual.crt_output=$out in batocera.conf"
		fi
	done
	if [ -n "$ok" ]; then
		echo "$ok" | tr ' ' '\n' | grep -v '^$' >"$CRT_DUAL_STATE_DIR/probe-ok" 2>/dev/null || true # write may fail (full /tmp); detect_outputs re-reads absence as no promotion
	else
		rm -f "$CRT_DUAL_STATE_DIR/probe-ok" 2>/dev/null || true # rm -f is idempotent; no error if already absent
	fi
	return 0
}
# ──────────────────────────────────────────────
# _switchres_api_path — resolved in src/owner/sr-owner.sh (THE one
# resolver: env override CRT_DUAL_API first, package-relative second);
# sr-owner sources this lib before any inject call.
# ──────────────────────────────────────────────

# DYNAMIC EDGE: this lib is the detection cascade + pure helpers; mode
# application is owned by SR-OWNER (src/owner/sr-owner.sh, 1 cervello = 1 file).
# No sourcing here (tests that need apply source sr-owner.sh directly).
